name: Test workflow  # 测试工作流

on:  # 触发配置开启
  push:  # push触发
    branches:  # 分支限制
      - main  # 仅main分支触发
  schedule:  # 定时任务配置
    - cron: "0 1 * * *"  # UTC时间1:00（北京时间9:00）
  workflow_dispatch:  # Actions标签页手动触发
    inputs:  # 输入参数配置
      force_sync:  # 参数名称
        description: 'Force immediate sync'  # 强制同步
        type: boolean  # 参数类型
        default: false  # 默认值

jobs:  # 工作定义
  test-job:  # 作业配置
    runs-on: ubuntu-latest  # 运行系统环境
    steps:  # 步骤序列
      - name: Print trigger info  # 步骤日志标识
        run: |  # 执行命令
          echo "Workflow triggered at $(date)"  # 输出带时间戳的触发信息
          echo "Force sync parameter: ${{ inputs.force_sync }}"  # 输出手动触发参数值
