name: Update Changelog to README  # 工作流名称

on:  # 触发配置
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"  # UTC时间1:00（北京时间9:00）
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force immediate sync'
        type: boolean
        default: false

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository  # 检出当前仓库
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Clone target repository  # 克隆目标仓库
        run: |
          git clone https://github.com/bia-pain-bache/BPB-Worker-Panel.git ./bpb-worker-panel

      - name: Generate README content  # 生成README内容
        id: generate-content
        run: |
          # 进入目标仓库目录
          cd ./bpb-worker-panel
          
          # 获取最新更新日志（假设文件为CHANGELOG.md）
          if [ -f CHANGELOG.md ]; then
            # 提取最新版本日志（取第一个#标题下的内容）
            LATEST_CHANGELOG=$(awk '/^# /{exit} {print}' CHANGELOG.md | sed '/^$/d')
            
            # 生成README格式内容
            README_CONTENT=$(cat <<EOF
            # BPB-Worker-Panel 更新日志
            
            ## 最新更新内容
            ${LATEST_CHANGELOG}
            
            > 更新时间：$(date -u +"%Y-%m-%d %H:%M:%S") UTC
            > 
            > [查看完整更新日志](https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/CHANGELOG.md)
            EOF
            )
            
            echo "README_CONTENT<<EOF" >> $GITHUB_ENV
            echo "$README_CONTENT" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md not found in target repository!"
            exit 1
          fi

      - name: Update README.md  # 更新README文件
        run: |
          # 写入当前仓库的README.md
          echo "${{ env.README_CONTENT }}" > README.md

      - name: Commit and push changes  # 提交并推送更改
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add README.md
          git commit -m "chore: 自动更新更新日志 [skip ci]" || exit 0
          git push origin main
